### ISSUE TITLE
Angle brackets not converted in (HTML) export

### ISSUE THREAD

**Issue by krzysz00** [evbacher/gd2md-html#55] opened 2019-12-08 19:47 UTC
The bug is exhibited by [the following minimal Google doc](https://docs.google.com/document/d/1jVpd6wQnn51vTUS-tlHvWjEP3dEpy9OOPDNYuamx66k/edit?usp=sharing)

Specifically, if I write `<text>` in a Google Doc, I expect that to be converted to `&lt;text&gt;` and not kept as-is, so that HTML parsers/sanitizers don't interpret it as a tag.

This applies to both Markdown and HTML export.

**Comment by evbacher** [comment] 2019-12-09 04:32
Note: this is a duplicate of issue #24. I attempted a fix, but something was wrong. It should be an easy fix, and I will try to address it soon (maybe I'll have some time during the holidays).

**Comment by evbacher** [comment] 2020-02-15 04:27
Fixed (#24 is a dup of this and also fixed). Please reopen if problems.

**Closed by evbacher** 2020-02-15 04:27 UTC
Labels: duplicate
