### ISSUE TITLE
HTML button trows error after forking 

### ISSUE THREAD

**Issue by alaherma** [evbacher/gd2md-html#84] opened 2021-01-14 05:36 UTC
I just followed the dev.md instruction to fork this repository, and i was testing worked properly to start editing some code and got this while runing my copy of this project

the error im getting is this:

`ScriptError: TypeError: el.getNestingLevel is not a function`

Any idea why is this happening and how can i fix it?

markdown button is working well. But im interested in the html capabilities.

this is how it looks:

![image](https://user-images.githubusercontent.com/16642593/104549163-e871fe80-55f7-11eb-92af-ae111ed1e622.png)

thank you for the help!!

**Comment by evbacher** [comment] 2021-01-14 15:35
Can you share (only need view permission) a doc that demonstrates this error? I suspect you have some non-list elements embedded in a list.

**Comment by martinsafar** [comment] 2021-03-17 08:25
I have the same problem. It seems that the problem was introduced with version 30. Version 29 is OK. If this helps.

**Comment by gjdickens** [comment] 2021-04-06 09:14
I was having the same problem.  I was able to work-around by commenting out lines 94-95 in HTML.gs:
```
var end = true;
gdc.maybeCloseList(elements[i-1], end);
```
I couldn't figure out what the problem is but I haven't noticed any impact from losing those two lines - maybe just edge cases?

**Comment by evbacher** [comment] 2021-04-06 17:58
You are correct. 1.0β30 was not live code. I'm not sure why I committed that change! The current version is live code from version of Docs to Markdown available in the Google Marketplace. Thanks to @gjdickens and @martinsafar for the clues on version and extraneous code.

I've added the live version (1.0β29) to the repo now.

**Closed by evbacher** 2021-04-06 17:58 UTC
